## 微信推送信息
wechat:
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
  wxTemplateUrl: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=

  ## 申请的测试公众号 appId 和 appSecret 注意，冒号后面有一个空格，冒号是英文的
  appId:
  appSecret:

  ## 对方的扫码id 注意，冒号后面有一个空格，冒号是英文的
  toUser:
  ##消息的id
  templateId:


## 天气
weather:
  url: https://autodev.openspeech.cn/csp/api/v2.1/weather?openId=aiuicus&clientType=android&sign=android&city=
  ## 对方的地区如：北京 注意，冒号后面有一个空格，冒号是英文的
  region: 北京


infor:
  ## 恋爱日期  格式如2022-01-20
  loveDate: 2022-01-20
  ## 生日
  birthday: 2022-01-20

## 申请的天行api参数值
tianApi:
