# name指的是这套工作流程的名称，可以自定义
name: CI

# on是指这套工作流程的trigger条件，即在push时触发
on:
  workflow_dispatch:
  push:
    # 当对分支master进行push操作的时候，这个工作流就被触发了
    branches: [ master ]
  pull_request:
    #只运行特定分支master
    branches: [ master ]
  schedule:
    # 定时任务
    - cron:  50 2 * * *


# jobs就是这套工作流程了
jobs:

  # build相当于<job_id>,可以自定义
  build:

    # 指定该job_id下的运行环境
    runs-on: ubuntu-latest

    # 制定运行步骤
    steps:
      # 先将仓库的代码checkout到环境中，github提供了checkout的方法，只需要我们加上这条即可
      - uses: actions/checkout@v1
      # 为接下来所执行的shell命名，可省略
      - name: executing
        run:
          # 指定所要运行的shell
          mvn -Dtest=PushTest#push -DskipTests=false test


